
Currently Loaded Modules:
  1) cmake/3.10.2                4) java/1.8.0_45     7) hdf5-parallel/1.8.16
  2) gcc/6.4.0                   5) cudatoolkit/9.1
  3) python/3.5-anaconda-4.1.1   6) openmpi/2.1.2

Solver Diverging!
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/users/brryan/.local/lib/python3.5/site-packages/arrayfire-3.6.0-py3.5.egg/arrayfire/array.py", line 551, in __del__
AttributeError: 'NoneType' object has no attribute 'get'
