
Currently Loaded Modules:
  1) cmake/3.10.2                4) java/1.8.0_45     7) hdf5-parallel/1.8.16
  2) gcc/6.4.0                   5) cudatoolkit/9.1
  3) python/3.5-anaconda-4.1.1   6) openmpi/2.1.2

/net/scratch3/brryan/anaconda_envs/my_bolt_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    h5f.close()
  File "/net/scratch3/brryan/anaconda_envs/my_bolt_env/lib/python3.5/site-packages/h5py/_hl/files.py", line 342, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5i.pyx", line 150, in h5py.h5i.dec_ref
RuntimeError: Can't decrement id ref count (unable to close file, errno = 122, error message = 'Disk quota exceeded')
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Signal received
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.9.3, Jul, 02, 2018 
[0]PETSC ERROR: Unknown Name on a  named ko031.localdomain by brryan Wed Aug  8 11:54:05 2018
[0]PETSC ERROR: Configure options --prefix=/turquoise/users/brryan/software/petsc_3.9.3_installation --with-debugging=0 COPTFLAGS="-O3 -march=native" --with-mpi-dir=/usr/projects/hpcsoft/toss3/kodiak/openmpi/2.1.2-gcc-6.4.0/ --with-hdf5=1 --with-hdf5-dir=/usr/projects/hpcsoft/toss3/kodiak/hdf5/1.8.16_gcc-6.4.0_openmpi-2.1.2/ --with-clean=1 --with-memalign=64 --with-64-bit-indices
[0]PETSC ERROR: #1 User provided function() line 0 in  unknown file
