
Currently Loaded Modules:
  1) cmake/3.10.2                4) java/1.8.0_45     7) hdf5-parallel/1.8.16
  2) gcc/6.4.0                   5) cudatoolkit/9.1
  3) python/3.5-anaconda-4.1.1   6) openmpi/2.1.2

/usr/projects/p18_ebhlight3d/bolt_env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    h5f = h5py.File(dfolder + '0000.h5', 'w')
  File "/usr/projects/p18_ebhlight3d/bolt_env/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/projects/p18_ebhlight3d/bolt_env/lib/python3.5/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
[ko033.localdomain:19686] 1 more process has sent help message help-opal-runtime.txt / opal_init:warn-fork
[ko033.localdomain:19686] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
slurmstepd: error: *** JOB 1055667 ON ko033 CANCELLED AT 2018-08-13T09:14:05 ***
